"""schema inicial

Revision ID: 993ae9d17454
Revises: 
Create Date: 2026-06-24 12:11:36.861407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '993ae9d17454'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escolas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('municipio', sa.String(length=120), nullable=True),
    sa.Column('codigo_inep', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_inep')
    )
    op.create_table('materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('niveis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.Enum('ADMIN', 'GESTOR', 'ALUNO', 'SUPORTE', name='perfilusuario'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('conteudos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', 'materia_id', name='uq_conteudo_nome_materia')
    )
    with op.batch_alter_table('conteudos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conteudos_materia_id'), ['materia_id'], unique=False)

    op.create_table('turmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('serie_id', sa.Integer(), nullable=False),
    sa.Column('ano_letivo', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['serie_id'], ['series.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turmas_escola_id'), ['escola_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_turmas_serie_id'), ['serie_id'], unique=False)

    op.create_table('alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('perfil_cognitivo', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alunos_turma_id'), ['turma_id'], unique=False)

    op.create_table('questoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enunciado', sa.Text(), nullable=False),
    sa.Column('imagem_url', sa.String(length=255), nullable=True),
    sa.Column('serie_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('conteudo_id', sa.Integer(), nullable=False),
    sa.Column('nivel_id', sa.Integer(), nullable=False),
    sa.Column('adaptacoes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conteudo_id'], ['conteudos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['nivel_id'], ['niveis.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['serie_id'], ['series.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questoes_conteudo_id'), ['conteudo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questoes_materia_id'), ['materia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questoes_nivel_id'), ['nivel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questoes_serie_id'), ['serie_id'], unique=False)
        batch_op.create_index('ix_questoes_serie_materia', ['serie_id', 'materia_id'], unique=False)

    op.create_table('simulados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gestor_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=160), nullable=False),
    sa.Column('parametros_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.Enum('RASCUNHO', 'GERADO', 'LIBERADO', 'FINALIZADO', name='statussimulado'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['gestor_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulados_gestor_id'), ['gestor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulados_turma_id'), ['turma_id'], unique=False)

    op.create_table('alternativas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('correta', sa.Boolean(), nullable=False),
    sa.Column('ordem_original', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alternativas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alternativas_questao_id'), ['questao_id'], unique=False)

    op.create_table('simulado_questoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulado_id', sa.Integer(), nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=False),
    sa.Column('ordem_questao', sa.Integer(), nullable=False),
    sa.Column('alternativas_ordem', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['simulado_id'], ['simulados.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulado_id', 'questao_id', name='uq_simulado_questao')
    )
    with op.batch_alter_table('simulado_questoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulado_questoes_questao_id'), ['questao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulado_questoes_simulado_id'), ['simulado_id'], unique=False)

    op.create_table('respostas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('simulado_id', sa.Integer(), nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=False),
    sa.Column('alternativa_id', sa.Integer(), nullable=False),
    sa.Column('correta', sa.Boolean(), nullable=False),
    sa.Column('respondida_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['alternativa_id'], ['alternativas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['simulado_id'], ['simulados.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aluno_id', 'simulado_id', 'questao_id', name='uq_resposta_unica')
    )
    with op.batch_alter_table('respostas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_respostas_aluno_id'), ['aluno_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_respostas_questao_id'), ['questao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_respostas_simulado_id'), ['simulado_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respostas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_respostas_simulado_id'))
        batch_op.drop_index(batch_op.f('ix_respostas_questao_id'))
        batch_op.drop_index(batch_op.f('ix_respostas_aluno_id'))

    op.drop_table('respostas')
    with op.batch_alter_table('simulado_questoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulado_questoes_simulado_id'))
        batch_op.drop_index(batch_op.f('ix_simulado_questoes_questao_id'))

    op.drop_table('simulado_questoes')
    with op.batch_alter_table('alternativas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alternativas_questao_id'))

    op.drop_table('alternativas')
    with op.batch_alter_table('simulados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulados_turma_id'))
        batch_op.drop_index(batch_op.f('ix_simulados_gestor_id'))

    op.drop_table('simulados')
    with op.batch_alter_table('questoes', schema=None) as batch_op:
        batch_op.drop_index('ix_questoes_serie_materia')
        batch_op.drop_index(batch_op.f('ix_questoes_serie_id'))
        batch_op.drop_index(batch_op.f('ix_questoes_nivel_id'))
        batch_op.drop_index(batch_op.f('ix_questoes_materia_id'))
        batch_op.drop_index(batch_op.f('ix_questoes_conteudo_id'))

    op.drop_table('questoes')
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alunos_turma_id'))

    op.drop_table('alunos')
    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turmas_serie_id'))
        batch_op.drop_index(batch_op.f('ix_turmas_escola_id'))

    op.drop_table('turmas')
    with op.batch_alter_table('conteudos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conteudos_materia_id'))

    op.drop_table('conteudos')
    op.drop_table('usuarios')
    op.drop_table('series')
    op.drop_table('niveis')
    op.drop_table('materias')
    op.drop_table('escolas')
    # ### end Alembic commands ###
